//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebTuyenDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public int employer_id { get; set; }
        public int user_id { get; set; }
        public int company_id { get; set; }
        public string role { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
